[variables]
NODE_VERSION = "18"

[phases.build]
dependsOn = ["install"]
cmds = ["cd backend && npx prisma generate"]

[phases.install]
cmds = ["cd backend && npm ci"]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"